export enum RestaurantsPageActionNames {
  RESTAURANTS_GET_ALL  = 'RESTAURANTS_GET_ALL',
  RESTAURANTS_GET_NEW  = 'RESTAURANTS_GET_NEW',
  RESTAURANTS_GET_POPULAR  = 'RESTAURANTS_GET_POPULAR',
  RESTAURANTS_GET_OPEN  = 'RESTAURANTS_GET_OPEN',
  RESTAURANTS_SET_FILTER = 'RESTAURANTS_SET_FILTER',
  
}